/-
Copyright (c) 2026 Mykola Palamarchuk. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mykola Palamarchuk
-/
import Lean

/-!
# Declaration manifest for the `ALT` package

Walks the compiled environment and records, for every declaration whose defining
module belongs to this package, the declaration's full name and that module.

    lake build                                  # the manifest reads .olean files
    lake env lean --run DeclManifest.lean [OUT] # default OUT: ../scripts/alt-decls.txt

This file is deliberately NOT part of the `ALT` library (it lives at the
workspace root, outside the `ALT.*` glob), so it is never imported by the
development it measures.

## One environment, one extension-loading import

The counting rule needs environment *extensions* (`isStructure`,
`isAuxRecursor`, `isNoConfusion` read tables that only `loadExts := true`
populates — without them they answer `false` to everything, so the filter would
silently stop filtering instead of failing).  Lean permits that once per
process: `importModules (loadExts := true)` clears the initializers flag it
consumed, so a second such import in the same process is refused.

That interlock used to force a two-process design here, because the modules
built against `Foundation` could not be co-imported with the Mathlib-side
umbrella (both dependencies declared a root `Matrix.map`, and importing two
different declarations under one name is an import-time error, not a
name-resolution one).  Upstream renamed theirs, so the umbrella `ALT` now
imports every module of the development and a single environment over that one
root sees the whole package.  One process, one extension-loading import.

## The counting rule

The filter below IS the counting rule: whatever survives it is what this
manifest calls a "declaration", and any figure quoted from the manifest means
exactly that.  A constant defined in a package module is counted unless it is

* internal — `Name.isInternal` (macro scopes and `_`-prefixed components:
  `…._cstage1`, `…._sunfold`, `…._proof_1`, …).  A `private` declaration is
  *authored*, not generated, so it is counted, under the source-level name its
  `_private.…` mangling hides (`privateToUserName?`);
* a constructor or a recursor — `ConstantInfo.ctorInfo` / `.recInfo`
  (`Foo.mk`, `Foo.rec`);
* an auxiliary recursor or no-confusion helper — `isAuxRecursor` /
  `isNoConfusion` (`Foo.recOn`, `Foo.casesOn`, `Foo.brecOn`, `Foo.below`, …);
* a structure projection — a name `S.f` where `S` is a structure with field `f`
  (including parent projections such as `S.toFoo`);
* a helper Lean reserves for an inductive or a constructor — a name `T.s` whose
  parent `T` is an inductive/constructor and whose last component `s` is one of
  `inductiveHelpers` below (`Foo.below`, `Foo.mk.injEq`, …).  Some of these are
  generated lazily and never reach the aux-recursor table, so the name test
  backs up the structural one;
* a helper generated *for* a definition — a name `d.s` whose parent `d` is a
  declaration and whose last component `s` is one of `definitionHelpers` below,
  or one of the numbered families `eq_1, eq_2, …` (equation lemmas), `match_1`,
  `match_1_1`, `match_1.splitter`, … (matchers and their splitters), `proof_1, …`
  (extracted proof terms).

Every test is structural where the environment knows the answer, and every
name-shaped test carries a witness — the parent it hangs off must really exist,
and for the inductive helpers must really be an inductive.  A rule that guesses
from names alone drops authored declarations: `ALT.RecursorAlgebra` authors a
`def rec`, and a blanket "drop anything called `rec`" ate it.

Everything else is counted: `def`, `abbrev`, `theorem`, `instance`, `structure`,
`inductive` — one constant per declaration written in the source — plus the
instances a `deriving` clause asks for.  An anonymous or `local instance` counts
under the name Lean gives it.  Constructors, projections and recursors are
*generated by* a written declaration and are therefore not counted separately: a
`structure` with five fields counts once, as a reader of the source counts it.

Grepping the sources for declaration keywords does *not* reproduce this count,
in either direction: with one sentence per line, docstring prose beginning
"theorem …" or "structure map is …" is counted as a declaration, while a
`noncomputable local instance` or an `@[simp] theorem` is missed.

## The field section

A structure's field projections are *citable* — `ParamNNO.orbit_injective` is a
name a paper may legitimately quote — but they are not *counted*: a `structure`
counts once no matter how many fields it has, as a reader of the source counts
it.  The two facts are not in tension, they are about different questions, and
the manifest answers both: the declaration lines are what the counts count, and
a trailing `field <module> <name>` section lists exactly the projections the
counting rule excludes.  Consumers that check citations read both sections;
consumers that quote a figure read the counts.  Private parents get the same
source-level-name treatment as everywhere else (`privateToUserName?`).
-/

open Lean

/-- Root module of the package being measured. -/
def packageRoot : Name := `ALT

/-- Default output path (the manifest is consumed outside this workspace). -/
def defaultOutput : System.FilePath := ".." / "scripts" / "alt-decls.txt"

/-- A module belongs to the package iff it is the root `ALT` or lies under it. -/
def isPackageModule (m : Name) : Bool :=
  m == packageRoot || packageRoot.isPrefixOf m

/-- Helper names Lean reserves for an inductive type or a constructor.  These are
dropped only when the parent really *is* an inductive or a constructor, which is
what makes a name-shaped test sound: for such a parent Lean owns these names, so
no authored declaration can occupy one.

Where the parent is anything else the name is fair game — `ALT.RecursorAlgebra`
authors a `def rec` (a bounded recursor, the point of the module), and a blanket
"drop anything called `rec`" rule silently ate it. -/
def inductiveHelpers : List String :=
  ["recOn", "casesOn", "below", "ibelow", "brecOn", "binductionOn",
   "noConfusion", "noConfusionType", "injEq", "inj", "sizeOf_spec", "sizeOf_inj",
   "ctorIdx", "toCtorIdx", "ofNat"]

/-- Helper names the equation compiler and the attribute machinery generate for a
definition.  Dropped when the parent is a declaration. -/
def definitionHelpers : List String :=
  ["eq_def", "eq_unfold", "induct", "fun_cases", "fun_cases_unfolding",
   "congr_simp", "splitter"]

/-- `numberedForm "match_" s` — a generated family indexed by one or more
numerals: `match_1`, and its splitters `match_1_1`, `match_1_2`, … -/
def numberedForm (prefix' s : String) : Bool :=
  s.startsWith prefix' &&
    let rest := s.drop prefix'.length
    !rest.isEmpty && rest.all fun c => c.isDigit || c == '_'

/-- The source-level name of a declaration: `private` mangles `foo` into
`_private.Mod.0.foo`, and it is the source-level name the counting rule reads. -/
def userName (n : Name) : Name := (privateToUserName? n).getD n

/-- Is `n` an inductive type or one of its constructors? -/
def isTypeLike (env : Environment) (n : Name) : Bool :=
  match env.find? n with
  | some (.inductInfo _) | some (.ctorInfo _) => true
  | _ => false

/-- The generated-name half of the counting rule: a helper name hangs off the
declaration it was generated for, so it is dropped only when that parent really
exists — as an inductive/constructor for `inductiveHelpers`, as any declaration
for `definitionHelpers`.  Without that witness the test is a guess about a name,
and guesses about names drop authored declarations.

The parent is sought under both the raw and the source-level name: a private
definition's matcher hangs off the mangled parent, while a *public* matcher's
equation lemmas are themselves private and hang off the unmangled one. -/
def isGeneratedName (env : Environment) (raw user : Name) : Bool :=
  match user with
  | .str _ s =>
      let parent (p : Name → Bool) := p raw.getPrefix || p user.getPrefix
      (parent (isTypeLike env ·) && inductiveHelpers.contains s)
        || (parent (env.contains ·)
              && (definitionHelpers.contains s
                    || numberedForm "eq_" s || numberedForm "match_" s
                    || numberedForm "proof_" s))
  | _ => true

/-- A structure projection `S.f` (including parent projections `S.toFoo`). -/
def isProjection (env : Environment) (n : Name) : Bool :=
  match n with
  | .str p f => isStructure env p && (getStructureFields env p).contains (Name.mkSimple f)
  | _ => false

/-- The counting rule: does this constant count as a declaration?  The
name-shaped tests read the source-level name, so that a `private` declaration is
counted while the helpers Lean generates *for* it still are not. -/
def counts (env : Environment) (n : Name) (ci : ConstantInfo) : Bool :=
  !((userName n).isInternal
    || isGeneratedName env n (userName n)
    || isAuxRecursor env n
    || isNoConfusion env n
    || (match ci with | .ctorInfo _ | .recInfo _ => true | _ => false)
    || isProjection env n)

/-- Is this constant a *field* — an authored structure projection?  These are the
citable-but-not-counted names of the field section: exactly the projections
`counts` excludes, minus anything internal or generated (a projection is neither,
but the rule states what it means rather than relying on that). -/
def isField (env : Environment) (n : Name) : Bool :=
  isProjection env n
    && !(userName n).isInternal
    && !isGeneratedName env n (userName n)

/-- Every `(module, declaration)` pair of the package recorded in `env`, every
`(module, field)` pair (citable, not counted — see the module docstring), and the
package modules `env` knows about (a module that declares nothing still counts as
a module, and is emitted with a count of 0). -/
def packagePairs (env : Environment) :
    Array (Name × Name) × Array (Name × Name) × Array Name := Id.run do
  let mods := env.header.moduleNames
  let data := env.header.moduleData
  let mut pairs := #[]
  let mut fields := #[]
  let mut seen := #[]
  for i in [0 : mods.size] do
    let m := mods[i]!
    if isPackageModule m then
      seen := seen.push m
      for n in data[i]!.constNames do
        if let some ci := env.find? n then
          if counts env n ci then
            pairs := pairs.push (m, userName n)
          else if isField env n then
            fields := fields.push (m, userName n)
  return (pairs, fields, seen)

/-- Sort the lines and drop adjacent duplicates. -/
def sortedNub (xs : Array String) : Array String := Id.run do
  let sorted := xs.qsort (fun a b => decide (a < b))
  let mut out := #[]
  for x in sorted do
    if out.back? != some x then
      out := out.push x
  return out

/-- Import roots and list the package's `(module, declaration)` pairs.

`loadExts` is REQUIRED and its default is `false`: `isStructure`,
`isAuxRecursor` and `isNoConfusion` read environment extensions, and an
environment imported without them answers `false` to all three — the filter
would silently stop filtering rather than fail. -/
unsafe def scanRoots (roots : Array Name) :
    IO (Array (Name × Name) × Array (Name × Name) × Array Name) := do
  enableInitializersExecution
  let env ← importModules (roots.map ({ module := · })) {} (loadExts := true)
  return packagePairs env

unsafe def main (args : List String) : IO Unit := do
  initSearchPath (← findSysroot)

  let out : System.FilePath :=
    match args with
    | path :: _ => path
    | [] => defaultOutput
  if let some dir := out.parent then
    unless ← dir.pathExists do
      throw <| IO.userError s!"output directory does not exist: {dir}\n\
        pass an output path: lake env lean --run DeclManifest.lean OUT"

  let (pairs, fields, mods) ← scanRoots #[packageRoot]

  let declLines := sortedNub <| pairs.map fun (m, n) => s!"{m} {n}"
  let fieldLines := sortedNub <| fields.map fun (m, n) => s!"{m} {n}"
  let modules := sortedNub <| mods.map toString

  let counted : Array (String × Nat) := modules.map fun m =>
    (m, declLines.foldl (init := 0) fun acc l =>
      if l.startsWith s!"{m} " then acc + 1 else acc)

  let header :=
    s!"# generated by formal/DeclManifest.lean; modules: {modules.size}; \
       total decls: {declLines.size}; \
       fields: {fieldLines.size} (structure projections: citable, NOT counted)"
  let moduleLines := counted.map fun (m, c) => s!"module {m} {c}"
  let fieldSection := fieldLines.map fun l => s!"field {l}"
  IO.FS.writeFile out <|
    String.intercalate "\n"
      (header :: (moduleLines ++ declLines ++ fieldSection).toList) ++ "\n"

  IO.eprintln s!"wrote {out}: {modules.size} modules, {declLines.size} declarations, \
    {fieldLines.size} fields"
